---
title: "Assignment 1 Question 1"
author: "Sheen Thusoo"
output: pdf_document
---

## e. [3 marks] If we replace $\sigma ^{4}$ with $\sigma_*^{4}=[\frac{1}{N-1}\sum_{u\epsilon \mathcal P^k}^{}\left ( y_{u} - \bar{y} \right )^{2}]^{2}$ in the definition of $\alpha \left ( \mathcal P  \right )$, does your answer to parts (b) and (d) change? Provide the details of your response.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

After changing $\sigma ^{4}$ to $\sigma_*^{4}=[\frac{1}{N-1}\sum_{u\epsilon \mathcal P^k}^{}\left ( y_{u} - \bar{y} \right )^{2}]^{2}$ in the definition of $\alpha \left ( \mathcal P  \right )$, the attribute becomes

$$
  \alpha \left ( y_{1}, ... , y_{N} \right ) = \frac{\frac{1}{N}\sum_{u\epsilon \mathcal P}^{}\left ( y_{u} - \bar{y} \right )^{4}}{ [\frac{1}{N-1}\sum_{u\epsilon \mathcal P}^{}\left ( y_{u} - \bar{y} \right )^{2}]^{2}} - 3
$$


First, we investigate if this new attribute is scale invariant, scale equivariant, or neither.

$$
  \alpha \left ( my_{1}, ... , my_{N} \right ) = \frac{\frac{1}{N}\sum_{u\epsilon \mathcal P}^{}\left ( my_{u} - m\bar{y} \right )^{4}}{ [\frac{1}{N-1}\sum_{u\epsilon \mathcal P}^{}\left ( my_{u} - m\bar{y} \right )^{2}]^{2}} - 3
$$
$$
  \alpha \left ( my_{1}, ... , my_{N} \right ) = \frac{\frac{1}{N}\sum_{u\epsilon \mathcal P}^{}\left ( my_{u} - m\bar{y} \right )^{4}}{ [\frac{1}{N-1}\sum_{u\epsilon \mathcal P}^{}\left ( my_{u} - m\bar{y} \right )^{2}]^{2}} - 3
$$
$$
  \alpha \left ( my_{1}, ... , my_{N} \right ) = \frac{\frac{m^4}{N}\sum_{u\epsilon \mathcal P}^{}\left ( y_{u} - \bar{y} \right )^{4}}{ [\frac{m^2}{N-1}\sum_{u\epsilon \mathcal P}^{}\left ( y_{u} - \bar{y} \right )^{2}]^{2}} - 3
$$

$$
  \alpha \left ( my_{1}, ... , my_{N} \right ) = \frac{m^4\frac{1}{N}\sum_{u\epsilon \mathcal P}^{}\left ( y_{u} - \bar{y} \right )^{4}}{ m^4[\frac{1}{N-1}\sum_{u\epsilon \mathcal P}^{}\left ( y_{u} - \bar{y} \right )^{2}]^{2}} - 3
$$

$$
  \alpha \left ( my_{1}, ... , my_{N} \right ) = \frac{\frac{1}{N}\sum_{u\epsilon \mathcal P}^{}\left ( y_{u} - \bar{y} \right )^{4}}{ [\frac{1}{N-1}\sum_{u\epsilon \mathcal P}^{}\left ( y_{u} - \bar{y} \right )^{2}]^{2}} - 3
$$

$$
  \alpha \left ( my_{1}, ... , my_{N} \right ) = \alpha \left ( y_{1}, ... , y_{N} \right )
$$

Therefore, this new attribute with $\sigma_* ^{4}$ is still scale invariant and hasn't changed from the answer in part b). This is because the $m$ constant still cancels out in the numerator and denominator. 

Next, we investigate if this new attribute is replication invariant, scale equivariant, or neither.

$$
  \alpha \left ( \mathcal P^k  \right )  = \frac{\frac{1}{N}\sum_{u\epsilon \mathcal P^k}^{}\left ( y_{u} - \bar{y} \right )^{4}}{ [\frac{1}{N-1}\sum_{u\epsilon \mathcal P^k}^{}\left ( y_{u} - \bar{y} \right )^{2}]^{2}} - 3
$$

$$
  \alpha \left ( \mathcal P^k  \right )  = \frac{\frac{1}{kN}\sum_{u\epsilon \mathcal P}^{}k\left ( y_{u} - \bar{y} \right )^{4}}{ [\frac{1}{k(N-1)}\sum_{u\epsilon \mathcal P}^{}k\left ( y_{u} - \bar{y} \right )^{2}]^{2}} - 3
$$

$$
  \alpha \left ( \mathcal P^k  \right )  = \frac{\frac{1}{kN}\sum_{u\epsilon \mathcal P}^{}k\left ( y_{u} - \bar{y} \right )^{4}}{ [\frac{1}{kN-1}\sum_{u\epsilon \mathcal P}^{}k\left ( y_{u} - \bar{y} \right )^{2}]^{2}} - 3
$$

$$
  \alpha \left ( \mathcal P^k  \right )  = \frac{\frac{k}{kN}\sum_{u\epsilon \mathcal P}^{}\left ( y_{u} - \bar{y} \right )^{4}}{ [\frac{k}{kN-1}\sum_{u\epsilon \mathcal P}^{}\left ( y_{u} - \bar{y} \right )^{2}]^{2}} - 3
$$

$$
  \alpha \left ( \mathcal P^k  \right )  = \frac{\frac{1}{N}\sum_{u\epsilon \mathcal P}^{}\left ( y_{u} - \bar{y} \right )^{4}}{ [\frac{k}{kN-1}\sum_{u\epsilon \mathcal P}^{}\left ( y_{u} - \bar{y} \right )^{2}]^{2}} - 3
$$

This equation does not simplify further. Therefore, this new attribute with $\sigma_* ^{4}$ is neither replication invariant nor equivariant and has changed from the answer in part d) which was replication invariant. This is because we have an extra $k$ coefficient on the $N$ term in the denominator and a $k$ constant in the numerator. These cannot be cancelled out.
